services:
  ollama:
    image: ollama/ollama:0.1.48
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  gradio:
    build:
      context: ./gradio
    ports:
      - "7860:7860"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - GRADIO_ANALYTICS_ENABLED=False
      - PYTHONUNBUFFERED=1
    volumes:
      - user_data:/root/.git-commit-at

  commit-at:
    build: .
    working_dir: /app
    depends_on:
      - ollama
      - redis
    stdin_open: true
    restart: no
    tty: true
    environment:
      - OLLAMA_URL=http://ollama:11434/
      - REDIS_URL=redis://redis:6379
    volumes:
      - user_data:/root/.git-commit-at

volumes:
  ollama-data:
  redis-data:
  user_data:
